
    create table client (
        document integer,
        enable boolean not null,
        id integer generated by default as identity,
        last_name varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table invoice (
        client_id integer,
        id integer generated by default as identity,
        total float(53) not null,
        created_at varchar(255),
        primary key (id)
    );

    create table invoicedetail (
        cantidad integer not null,
        id integer generated by default as identity,
        invoice_id integer,
        precio float(53) not null,
        product_id integer,
        primary key (id)
    );

    create table product (
        enable boolean not null,
        id integer generated by default as identity,
        price integer,
        stock integer,
        code varchar(255),
        description varchar(255),
        title varchar(255),
        primary key (id)
    );

    alter table if exists invoice 
       add constraint FK6y01j0975eqwmnb0gckttrbj2 
       foreign key (client_id) 
       references client;

    alter table if exists invoicedetail 
       add constraint FKa4105oreoul6699r5qrj9rsc0 
       foreign key (invoice_id) 
       references invoice;

    alter table if exists invoicedetail 
       add constraint FKhvdbc46lyj2g968peplws8frc 
       foreign key (product_id) 
       references product;